import { MICRODRIVE_FIRST_LESSON, MICRODRIVE_EXTRA_LESSONS } from "./guide-microdrives.js";

function lesson(definition) {
  return Object.freeze({
    ...definition,
    keywords: Object.freeze(definition.keywords),
  });
}

export const GUIDE_LESSONS = Object.freeze([
  lesson({
    id: "primeiro-comando",
    chapterNumber: 1,
    chapter: "Primeiros cinco minutos",
    manualReference: "Capítulo 1",
    title: "Fazer o QL responder",
    summary: "Envie uma instrução imediata ao SuperBASIC e veja a resposta no ecrã.",
    explanation: "PRINT apresenta texto ou resultados no ecrã. As aspas indicam que o conteúdo deve ser tratado como texto, e não como o nome de uma variável.",
    experiment: "Troque a mensagem entre aspas e execute novamente.",
    kind: "command",
    code: 'PRINT "OLA, SINCLAIR QL"',
    accent: "green",
    keywords: ["print", "texto", "comando", "consola"],
  }),
  lesson({
    id: "primeiro-programa",
    chapterNumber: 2,
    chapter: "Primeiros programas",
    manualReference: "Capítulo 2",
    title: "Guardar instruções num programa",
    summary: "Construa um pequeno programa numerado e deixe-o preparado para RUN.",
    explanation: "As linhas numeradas ficam guardadas na memória do SuperBASIC. O QL executa-as por ordem quando recebe RUN; NEW apaga o programa anterior.",
    experiment: "Altere o valor de nome$ ou acrescente uma linha 140 com outra mensagem.",
    kind: "program",
    code: [
      "100 CLS",
      '110 LET nome$ = "QL"',
      '120 PRINT "BEM-VINDO AO SINCLAIR "; nome$',
      '130 PRINT "ESTE PROGRAMA JA ESTA NA MEMORIA"',
    ].join("\n"),
    accent: "yellow",
    keywords: ["programa", "linhas", "run", "let", "variavel"],
  }),
  lesson({
    id: "estrela-de-cores",
    chapterNumber: 3,
    chapter: "Desenhar no ecrã",
    manualReference: "Capítulo 3",
    title: "Uma estrela de linhas coloridas",
    summary: "Combine cor, números aleatórios, desenho e repetição num exemplo visual.",
    explanation: "O QL usa coordenadas independentes da resolução. FOR repete o desenho, RND escolhe cores e pontos, e LINE traça cada raio da estrela.",
    experiment: "Mude 24 para 60, ou substitua PAPER 0 por PAPER 7 para observar o contraste.",
    kind: "program",
    code: [
      "100 MODE 8",
      "110 PAPER 0 : CLS",
      "120 FOR raio = 1 TO 24",
      "130   INK RND(1 TO 7)",
      "140   LINE 50,50 TO RND(100),RND(100)",
      "150 END FOR raio",
    ].join("\n"),
    accent: "red",
    keywords: ["grafico", "linha", "line", "for", "rnd", "cor"],
  }),
  lesson({
    id: "strings-com-significado",
    chapterNumber: 4,
    chapter: "Texto e variáveis",
    manualReference: "Capítulo 4",
    title: "Construir e explorar texto",
    summary: "Junte palavras, conte caracteres e extraia letras de uma string.",
    explanation: "As variáveis terminadas em $ guardam texto. O operador & concatena strings, LEN mede-as e os parênteses permitem selecionar caracteres.",
    experiment: "Troque QUANTUM e LEAP pelo seu nome e apelido.",
    kind: "program",
    code: [
      "100 CLS",
      '110 LET first$ = "QUANTUM"',
      '120 LET second$ = "LEAP"',
      '130 LET name$ = first$ & " " & second$',
      "140 PRINT name$",
      '150 PRINT "CHARACTERS:" ! LEN(name$)',
      '160 PRINT "INITIALS:" ! first$(1) & second$(1)',
    ].join("\n"),
    accent: "green",
    keywords: ["string", "texto", "len", "concatenar", "variavel"],
  }),
  lesson(MICRODRIVE_FIRST_LESSON),
  lesson({
    id: "guardar-no-microdrive",
    chapterNumber: 5,
    chapter: "Microdrives, do início à cópia",
    manualReference: "Capítulo 5",
    title: "Guardar o programa no Microdrive",
    summary: "Grave no mdv1_ o programa que está atualmente na memória.",
    explanation: "Faça primeiro Começar aqui: cartucho novo e FORMAT. SAVE escreve o programa SuperBASIC num ficheiro: mdv1_guia significa guia na unidade 1. Antes de guardar, use LIST para confirmar que há um programa em memória. Para um ensaio simples, escreva a linha 100 PRINT \"OLA DO MICRODRIVE\" e depois execute SAVE. Os comandos sem número de linha são instruções imediatas; a linha 100 fica no programa.",
    experiment: "Depois de guardar, experimente DIR mdv1_ para confirmar que o ficheiro existe.",
    note: "MDV1 tem de estar inserida, formatada e com escrita permitida. Se guia já existir, escolha SAVE mdv1_guia_v2. SAVE não exporta a imagem para o computador: espere que o motor pare e use Exportar .mdv.",
    writesMicrodrive: true,
    kind: "command",
    code: "SAVE mdv1_guia",
    accent: "yellow",
    keywords: ["save", "guardar", "microdrive", "mdv1", "dir", "load"],
  }),
  lesson({
    id: "formatar-segundo-microdrive",
    chapterNumber: 5,
    chapter: "Microdrives, do início à cópia",
    manualReference: "Capítulo 5 · Microdrives",
    title: "Preparar um cartucho em MDV2",
    summary: "Monte dois cartuchos e prepare a unidade de destino para as cópias.",
    explanation: "Abra Software. Selecione o cartucho de origem e escolha Inserir em MDV1. No gestor, selecione MDV2, escolha Novo cartucho e crie um cartucho virgem: fica logo inserido e com escrita permitida. Execute FORMAT para lhe dar o nome trabalho. Inserir conserva o programa em memória; Reiniciar e arrancar de MDV1 reinicia a máquina e procura mdv1_boot. A atividade de MDV1 não impede inserir um cartucho na MDV2 vazia e parada.",
    experiment: "Quando o motor parar, use DIR mdv2_ para ver o nome e o espaço disponível.",
    note: "FORMAT apaga todo o conteúdo de MDV2. Use um cartucho virgem ou dispensável. Não formate os cartuchos de software para os carregar. Aguarde o fim da operação; Guardar .mdv conserva o resultado no computador.",
    writesMicrodrive: true,
    microdriveTargets: "mdv2_",
    formatsMicrodrive: true,
    kind: "command",
    code: "FORMAT mdv2_trabalho",
    accent: "red",
    keywords: ["format", "formatar", "virgem", "microdrive", "mdv2", "duas unidades", "cartucho"],
  }),
  lesson({
    id: "diretorios-dos-dois-microdrives",
    chapterNumber: 5,
    chapter: "Microdrives, do início à cópia",
    manualReference: "Capítulo 5 · Microdrives",
    title: "Consultar as duas unidades",
    summary: "Veja os ficheiros de MDV1 e MDV2 sem trocar cartuchos.",
    explanation: "O prefixo mdv1_ ou mdv2_ escolhe a unidade. O sublinhado faz parte do nome. DIR mostra o nome do cartucho, o espaço e os ficheiros. Dois cartuchos podem estar montados ao mesmo tempo; o QDOS alterna o motor que utiliza. A luz vermelha acompanha a seleção do motor, incluindo a procura de setores e o tempo até parar, mesmo quando já apareceu texto no ecrã.",
    experiment: "Experimente DIR mdv2_ sozinho. Este emulador tem apenas as duas unidades internas do QL: mdv1_ e mdv2_.",
    note: "Requer dois cartuchos formatados e montados. Um cartucho virgem precisa de FORMAT; um cartucho de software existente não. A biblioteca indica qual o motor em marcha.",
    kind: "command",
    code: "DIR mdv1_ : DIR mdv2_",
    accent: "green",
    keywords: ["dir", "diretorio", "listar", "microdrive", "mdv1", "mdv2", "luz", "motor"],
  }),
  lesson({
    id: "copiar-entre-microdrives",
    chapterNumber: 5,
    chapter: "Microdrives, do início à cópia",
    manualReference: "Capítulo 5 · Microdrives",
    title: "Copiar de MDV1 para MDV2",
    summary: "Faça uma cópia do programa guia conservando o original.",
    explanation: "Use primeiro Guardar o programa no Microdrive para criar mdv1_guia. Com os dois cartuchos montados e MDV2 formatado e gravável, COPY lê da origem e escreve no destino. COPY conserva o cabeçalho QDOS, incluindo o tipo e o espaço de dados de executáveis. COPY_N destina-se a cópias sem cabeçalho; use COPY entre microdrives.",
    experiment: "Confirme com DIR mdv2_ e experimente LOAD mdv2_guia. Para copiar outro ficheiro, substitua guia nos dois nomes.",
    note: "A origem pode ficar Protegida. O destino precisa de espaço livre e não deve já conter guia: escolha outro nome ou apague deliberadamente a cópia antiga. Aguarde que os motores parem e use Guardar .mdv em MDV2. COPY copia um ficheiro; repita para cada ficheiro, incluindo boot e os dados necessários. A ROM base não oferece cópia com curingas de todo o cartucho.",
    writesMicrodrive: true,
    microdriveTargets: "mdv2_",
    kind: "command",
    code: "COPY mdv1_guia TO mdv2_guia",
    accent: "yellow",
    keywords: ["copy", "copy_n", "copiar", "copia", "backup", "microdrive", "mdv1", "mdv2", "duas unidades"],
  }),
  lesson({
    id: "carregar-do-segundo-microdrive",
    chapterNumber: 5,
    chapter: "Microdrives, do início à cópia",
    manualReference: "Capítulo 5 · Microdrives",
    title: "Recuperar o programa guardado",
    summary: "Carregue de MDV2 uma cópia do programa guia.",
    explanation: "Depois do exemplo de cópia, LOAD lê guia de MDV2 para a memória do SuperBASIC. Use LIST para o examinar e RUN para o executar. LRUN mdv2_guia combina carregamento e execução. O programa deve ter sido gravado com SAVE; executáveis em código máquina usam EXEC ou EXEC_W, não LOAD.",
    experiment: "Depois de LOAD, escreva LIST. Para executar diretamente, experimente LRUN mdv2_guia.",
    note: "Requer o ficheiro guia em MDV2. LOAD substitui o programa em memória; guarde primeiro o que quiser conservar. Não é necessário desproteger um cartucho para ler.",
    replacesProgram: true,
    kind: "command",
    code: "LOAD mdv2_guia",
    accent: "yellow",
    keywords: ["load", "lrun", "run", "list", "carregar", "microdrive", "mdv2", "executavel"],
  }),
  lesson({
    id: "arrancar-software-microdrive",
    chapterNumber: 5,
    chapter: "Microdrives, do início à cópia",
    manualReference: "Capítulo 5 · Microdrives",
    title: "Arrancar software e reconhecer erros",
    summary: "Use o BOOT do cartucho e distinga programas BASIC de executáveis.",
    explanation: "DIR mdv1_ permite confirmar se existe boot. LRUN mdv1_boot carrega e executa esse programa BASIC. Em alternativa, Reiniciar e arrancar de MDV1, no gestor, usa o cartucho já inserido, reinicia o QL e envia F1. Para um executável QDOS use, por exemplo, EXEC_W mdv1_programa. Alguns programas esperam dados em MDV2: insira também o segundo cartucho antes do arranque.",
    experiment: "Consulte o BOOT com LOAD mdv1_boot e LIST para descobrir os nomes e as unidades que utiliza, se quiser examiná-lo antes de executar.",
    note: "Not found: confirme a unidade e o nome com DIR. Bad medium: confirme que a imagem é válida; não use FORMAT para reparar software que quer conservar. Bad parameter ao usar EXEC: o ficheiro pode não ter cabeçalho de executável. Not implemented ou Out of memory podem indicar extensões ou mais RAM exigidas pelo programa. O emulador tem 128 KiB; a conversão de ZIP/QLPAK não acrescenta Toolkit II nem altera referências a discos dentro de todos os programas.",
    replacesProgram: true,
    kind: "command",
    code: "LRUN mdv1_boot",
    accent: "green",
    keywords: ["boot", "exec", "exec_w", "lrun", "erro", "carregar", "microdrive", "bad medium", "not found"],
  }),
  lesson({
    id: "copiar-de-volta-microdrive",
    chapterNumber: 5,
    chapter: "Microdrives, do início à cópia",
    manualReference: "Capítulo 5 · Microdrives",
    title: "Copiar de volta com outro nome",
    summary: "Leia de MDV2 e crie guia_copia em MDV1.",
    explanation: "A origem e o destino podem trocar de papel. O nome depois de TO pode ser diferente: guia_copia evita substituir o ficheiro guia original. O comando não altera o programa BASIC em memória.",
    experiment: "Confirme com DIR mdv1_. Também pode copiar dentro de uma unidade com COPY mdv2_guia TO mdv2_guia_copia, se houver espaço.",
    note: "Requer a cópia guia em MDV2 e MDV1 gravável, com espaço livre e sem um ficheiro guia_copia anterior. Quando terminar, guarde a imagem de MDV1 para conservar esta nova cópia.",
    writesMicrodrive: true,
    microdriveTargets: "mdv1_",
    kind: "command",
    code: "COPY mdv2_guia TO mdv1_guia_copia",
    accent: "green",
    keywords: ["copy", "copiar", "copia", "renomear", "microdrive", "mdv1", "mdv2"],
  }),
  lesson({
    id: "apagar-copia-microdrive",
    chapterNumber: 5,
    chapter: "Microdrives, do início à cópia",
    manualReference: "Capítulo 5 · Microdrives",
    title: "Apagar apenas a cópia de ensaio",
    summary: "Liberte o espaço de guia_copia em MDV1.",
    explanation: "DELETE remove o ficheiro indicado, mantendo os restantes. Use DIR mdv1_ antes para confirmar o nome. Para repetir uma cópia com o mesmo destino, pode apagar primeiro esse destino, se tiver a certeza de que já não precisa dele.",
    experiment: "Depois de DELETE, confirme com DIR mdv1_ que guia continua presente.",
    note: "Este exemplo apaga mdv1_guia_copia, criado na lição anterior. Requer MDV1 gravável. Não há anulação no QDOS; mantenha uma imagem exportada se quiser poder recuperar o conteúdo anterior.",
    writesMicrodrive: true,
    microdriveTargets: "mdv1_",
    kind: "command",
    code: "DELETE mdv1_guia_copia",
    accent: "red",
    keywords: ["delete", "apagar", "espaco", "microdrive", "mdv1", "copia"],
  }),
  ...MICRODRIVE_EXTRA_LESSONS.map(lesson),
  lesson({
    id: "arrays-e-ciclos-for",
    chapterNumber: 6,
    chapter: "Listas e repetições",
    manualReference: "Capítulo 6",
    title: "Seis lançamentos num array",
    summary: "Guarde uma sequência de números e percorra-a com FOR.",
    explanation: "DIM reserva uma coleção indexada. O primeiro ciclo preenche o array e o segundo recupera cada posição, mostrando como dados e repetição trabalham juntos.",
    experiment: "Aumente o array para 12 posições e simule dois dados com RND(1 TO 6)+RND(1 TO 6).",
    kind: "program",
    code: [
      "100 DIM score(6)",
      "110 FOR k = 1 TO 6 : LET score(k) = RND(1 TO 6)",
      '120 PRINT "SIX THROWS:"',
      "130 FOR k = 1 TO 6 : PRINT ! score(k) !",
    ].join("\n"),
    accent: "red",
    keywords: ["array", "dim", "for", "rnd", "lista", "ciclo"],
  }),
  lesson({
    id: "primeira-procedure",
    chapterNumber: 7,
    chapter: "Procedimentos",
    manualReference: "Capítulo 7",
    title: "Dar um nome a uma tarefa",
    summary: "Defina um procedimento reutilizável que desenha um quadrado.",
    explanation: "DEFine PROCedure cria uma nova instrução SuperBASIC. Os parâmetros deixam o mesmo procedimento trabalhar com tamanhos e posições diferentes.",
    experiment: "Acrescente square 20,60,20 antes da definição para desenhar outro quadrado.",
    kind: "program",
    code: [
      "100 PAPER 0 : CLS",
      "110 INK 4",
      "120 square 30,35,35",
      "130 DEFine PROCedure square(side,x,y)",
      "140   LINE x,y TO x+side,y TO x+side,y+side TO x,y+side TO x,y",
      "150 END DEFine",
    ].join("\n"),
    accent: "green",
    keywords: ["procedure", "define", "parametros", "line", "subrotina"],
  }),
  lesson({
    id: "superbasic-estruturado",
    chapterNumber: 8,
    chapter: "Programas estruturados",
    manualReference: "Capítulo 8",
    title: "Decidir sem saltos",
    summary: "Use um bloco IF completo dentro de um ciclo legível.",
    explanation: "A forma estruturada IF…ELSE…END IF mantém os caminhos do programa visíveis. MOD permite distinguir números pares de ímpares.",
    experiment: "Mude o limite do FOR ou teste divisibilidade por 3.",
    kind: "program",
    code: [
      "100 FOR value = 1 TO 12",
      "110   IF value MOD 2 = 0 THEN",
      '120     PRINT value ! "EVEN"',
      "130   ELSE",
      '140     PRINT value ! "ODD"',
      "150   END IF",
      "160 END FOR value",
    ].join("\n"),
    accent: "yellow",
    keywords: ["if", "else", "end if", "mod", "estrutura", "decisao"],
  }),
  lesson({
    id: "tipos-e-aritmetica",
    chapterNumber: 9,
    chapter: "Números e tipos",
    manualReference: "Capítulo 9",
    title: "Dividir, arredondar e medir",
    summary: "Compare divisão real, inteira, resto e raiz quadrada.",
    explanation: "DIV devolve o quociente inteiro e MOD o resto. SQRT calcula a raiz; INT ajuda a construir arredondamentos. O sufixo % identifica uma variável inteira.",
    experiment: "Experimente outros valores de total e groups% e preveja cada resultado.",
    kind: "program",
    code: [
      "100 LET total = 17",
      "110 LET groups% = 5",
      '120 PRINT "DIVISION:" ! total/groups%',
      '130 PRINT "INTEGER DIVISION:" ! total DIV groups%',
      '140 PRINT "REMAINDER:" ! total MOD groups%',
      '150 PRINT "SQUARE ROOT:" ! SQRT(total)',
      '160 PRINT "ROUNDED:" ! INT(SQRT(total)+0.5)',
    ].join("\n"),
    accent: "red",
    keywords: ["numero", "integer", "div", "mod", "sqrt", "int", "aritmetica"],
  }),
  lesson({
    id: "logica-booleana",
    chapterNumber: 10,
    chapter: "Lógica",
    manualReference: "Capítulo 10",
    title: "Uma tabela de verdade",
    summary: "Veja AND, OR e XOR em todas as combinações de zero e um.",
    explanation: "Os operadores lógicos combinam condições. Esta pequena tabela torna visível quando cada operador produz falso (0) ou verdadeiro (1).",
    experiment: "Acrescente uma coluna com NOT a e observe os valores produzidos.",
    kind: "program",
    code: [
      '100 PRINT "A B  AND OR XOR"',
      "110 FOR a = 0 TO 1",
      "120   FOR b = 0 TO 1",
      "130     PRINT a ! b ! (a AND b) ! (a OR b) ! (a XOR b)",
      "140   END FOR b",
      "150 END FOR a",
    ].join("\n"),
    accent: "green",
    keywords: ["logica", "and", "or", "xor", "not", "booleano"],
  }),
  lesson({
    id: "fatiar-e-procurar-strings",
    chapterNumber: 11,
    chapter: "Operações com strings",
    manualReference: "Capítulo 11",
    title: "Procurar e substituir palavras",
    summary: "Selecione intervalos de caracteres e localize texto com INSTR.",
    explanation: "Uma fatia como text$(10 TO 16) lê ou substitui parte de uma string. INSTR devolve a posição em que uma expressão aparece.",
    experiment: "Procure LEAP e substitua outra fatia por uma palavra com o mesmo comprimento.",
    kind: "program",
    code: [
      '100 LET text$ = "SINCLAIR QUANTUM LEAP"',
      "110 PRINT text$(1 TO 8)",
      "120 PRINT text$(10 TO 16)",
      '130 LET pos = "QUANTUM" INSTR text$',
      '140 PRINT "FOUND AT:" ! pos',
      '150 LET text$(10 TO 16) = "DIGITAL"',
      "160 PRINT text$",
    ].join("\n"),
    accent: "yellow",
    keywords: ["string", "instr", "fatia", "slice", "substituir", "procurar"],
  }),
  lesson({
    id: "circulos-e-cor",
    chapterNumber: 12,
    chapter: "Gráficos e janelas",
    manualReference: "Capítulo 12",
    title: "Círculos concêntricos",
    summary: "Explore a paleta do QL com círculos de raio crescente.",
    explanation: "CIRCLE recebe o centro e o raio em coordenadas gráficas. INK escolhe a cor usada por cada nova circunferência.",
    experiment: "Mude o centro ou use valores de raio mais próximos para criar um alvo.",
    kind: "program",
    code: [
      "100 MODE 8",
      "110 PAPER 0 : CLS",
      "120 FOR colour = 1 TO 7",
      "130   INK colour",
      "140   CIRCLE 50,50,5+colour*5",
      "150 END FOR colour",
    ].join("\n"),
    accent: "red",
    keywords: ["circle", "circulo", "ink", "paper", "grafico", "cor"],
  }),
  lesson({
    id: "janela-independente",
    chapterNumber: 12,
    chapter: "Gráficos e janelas",
    manualReference: "Capítulo 12",
    title: "Abrir uma janela independente",
    summary: "Crie um canal de ecrã, pinte-o e feche-o sem afetar a consola principal.",
    explanation: "Os canais # permitem dirigir cada comando para um dispositivo ou janela. OPEN cria a janela #4; comandos com #4 atuam apenas nela.",
    experiment: "Altere as dimensões de scr_ ou as cores de PAPER e INK.",
    kind: "program",
    code: [
      "100 OPEN #4,scr_220x100a20x20",
      "110 PAPER #4,1 : INK #4,7 : CLS #4",
      "120 BORDER #4,4,2",
      '130 PRINT #4,"A WINDOW OF ITS OWN"',
      "140 PAUSE 100",
      "150 CLOSE #4",
    ].join("\n"),
    accent: "green",
    keywords: ["window", "janela", "channel", "canal", "open", "screen", "scr"],
  }),
  lesson({
    id: "ficheiro-sequencial",
    chapterNumber: 12,
    chapter: "Canais e ficheiros",
    manualReference: "Capítulo 12",
    title: "Escrever e ler um ficheiro",
    summary: "Guarde dez resultados num ficheiro sequencial e leia-os de volta.",
    explanation: "OPEN_NEW cria o ficheiro, PRINT # escreve no respetivo canal e OPEN_IN volta a abri-lo para leitura. CLOSE liberta sempre o canal no fim.",
    experiment: "Guarde cubos em vez de quadrados ou aumente a quantidade de valores.",
    note: "Requer um cartucho mdv1_ formatado e com escrita ativa. OPEN_NEW dá erro se guide_data já existir: use outro nome ou apague deliberadamente o ficheiro anterior com DELETE mdv1_guide_data.",
    writesMicrodrive: true,
    kind: "program",
    code: [
      "100 OPEN_NEW #6,mdv1_guide_data",
      "110 FOR n = 1 TO 10",
      "120   PRINT #6,n*n",
      "130 END FOR n",
      "140 CLOSE #6",
      "150 OPEN_IN #6,mdv1_guide_data",
      "160 FOR n = 1 TO 10",
      "170   INPUT #6,value",
      "180   PRINT ! value !",
      "190 END FOR n",
      "200 CLOSE #6",
    ].join("\n"),
    accent: "green",
    keywords: ["ficheiro", "file", "open_new", "open_in", "input", "microdrive", "mdv1"],
  }),
  lesson({
    id: "dois-canais-dois-microdrives",
    chapterNumber: 12,
    chapter: "Canais e ficheiros",
    manualReference: "Capítulo 12 · Microdrives",
    title: "Ler de uma unidade e escrever na outra",
    summary: "Abra dois canais em simultâneo e transfira os valores até ao fim do ficheiro, usando EOF.",
    explanation: "Execute primeiro Escrever e ler um ficheiro para criar mdv1_guide_data. #6 lê de MDV1 e #7 escreve em MDV2. Os dois canais ficam abertos; o QDOS gere os buffers e alterna os motores. EOF é testado antes de cada INPUT, para não ler além do fim mesmo que a quantidade de valores mude. PRINT escreve o valor e CLOSE fecha os canais. Para uma cópia exata de qualquer ficheiro, use COPY.",
    experiment: "Mude PRINT #7,value para PRINT #7,value*2, escolha um novo nome de destino e execute novamente para transformar os valores durante a cópia.",
    note: "Requer guide_data com valores numéricos, um por linha, em MDV1, e MDV2 formatado e gravável, sem guide_copy anterior. O exemplo anterior cria dez valores, mas este ciclo aceita outra quantidade. Depois de terminar, espere pela paragem dos motores e guarde MDV2. Se interromper o programa, feche os canais abertos com CLOSE #6 e CLOSE #7 antes de trocar cartuchos.",
    writesMicrodrive: true,
    microdriveTargets: "mdv2_",
    kind: "program",
    code: [
      "100 OPEN_IN #6,mdv1_guide_data",
      "110 OPEN_NEW #7,mdv2_guide_copy",
      "120 REPeat copiar",
      "125   IF EOF(#6) THEN EXIT copiar",
      "130   INPUT #6,value",
      "140   PRINT #7,value",
      "150 END REPeat copiar",
      "160 CLOSE #7",
      "170 CLOSE #6",
      '180 PRINT "COPIA CONCLUIDA"',
    ].join("\n"),
    accent: "yellow",
    keywords: ["canal", "open_in", "open_new", "close", "eof", "copiar", "microdrive", "mdv1", "mdv2", "simultaneo"],
  }),
  lesson({
    id: "array-bidimensional",
    chapterNumber: 13,
    chapter: "Arrays multidimensionais",
    manualReference: "Capítulo 13",
    title: "Uma tabela de multiplicação",
    summary: "Organize valores em linhas e colunas com um array bidimensional.",
    explanation: "DIM table(3,3) cria uma grelha. Dois índices identificam cada célula e dois ciclos percorrem as suas linhas e colunas.",
    experiment: "Transforme a tabela 3×3 numa tabela 6×6.",
    kind: "program",
    code: [
      "100 DIM table(3,3)",
      "110 FOR row = 1 TO 3",
      "120   FOR col = 1 TO 3",
      "130     LET table(row,col) = row*col",
      "140     PRINT ! table(row,col) !",
      "150   END FOR col",
      "160   PRINT",
      "170 END FOR row",
    ].join("\n"),
    accent: "yellow",
    keywords: ["array", "dim", "matriz", "tabela", "linha", "coluna"],
  }),
  lesson({
    id: "estruturas-aninhadas",
    chapterNumber: 14,
    chapter: "Estruturas aninhadas",
    manualReference: "Capítulo 14",
    title: "Uma grelha de pontos coloridos",
    summary: "Combine dois ciclos para percorrer coordenadas em duas dimensões.",
    explanation: "O ciclo exterior escolhe cada linha e o interior percorre as colunas. Aninhar estruturas permite exprimir padrões complexos sem repetir código.",
    experiment: "Diminua STEP para 5 ou substitua POINT por CIRCLE x,y,2.",
    kind: "program",
    code: [
      "100 PAPER 0 : CLS",
      "110 FOR y = 20 TO 80 STEP 10",
      "120   FOR x = 20 TO 80 STEP 10",
      "130     INK RND(1 TO 7)",
      "140     POINT x,y",
      "150   END FOR x",
      "160 END FOR y",
    ].join("\n"),
    accent: "red",
    keywords: ["aninhado", "nested", "for", "point", "grelha", "step"],
  }),
  lesson({
    id: "selecao-multipla",
    chapterNumber: 14,
    chapter: "Estruturas aninhadas",
    manualReference: "Capítulo 14",
    title: "Escolher entre vários caminhos",
    summary: "Use SELect ON para tratar alternativas de forma clara.",
    explanation: "SELect ON reúne várias escolhas relacionadas num único bloco. Cada cláusula ON trata um valor possível sem uma cadeia extensa de IF.",
    experiment: "Acrescente mais direções e aumente o intervalo de RND.",
    kind: "program",
    code: [
      "100 LET choice = RND(1 TO 4)",
      "110 SELect ON choice",
      "120   ON choice = 1",
      '130     PRINT "NORTH"',
      "140   ON choice = 2",
      '150     PRINT "EAST"',
      "160   ON choice = 3",
      '170     PRINT "SOUTH"',
      "180   ON choice = 4",
      '190     PRINT "WEST"',
      "200 END SELect",
    ].join("\n"),
    accent: "green",
    keywords: ["select", "on", "escolha", "alternativa", "condicao"],
  }),
  lesson({
    id: "funcao-com-resultado",
    chapterNumber: 15,
    chapter: "Procedimentos e funções",
    manualReference: "Capítulo 15",
    title: "Criar uma função",
    summary: "Defina uma função cube que calcula e devolve um valor.",
    explanation: "Uma FuNction pode ser usada dentro de uma expressão. RETurn entrega o resultado ao ponto em que a função foi chamada.",
    experiment: "Crie uma função square ou altere o intervalo do ciclo.",
    kind: "program",
    code: [
      "100 FOR n = 1 TO 8",
      "110   PRINT n ! cube(n)",
      "120 END FOR n",
      "130 DEFine FuNction cube(value)",
      "140   RETurn value*value*value",
      "150 END DEFine",
    ].join("\n"),
    accent: "yellow",
    keywords: ["function", "funcao", "define", "return", "resultado"],
  }),
  lesson({
    id: "parametros-e-variaveis-locais",
    chapterNumber: 15,
    chapter: "Procedimentos e funções",
    manualReference: "Capítulo 15",
    title: "Parâmetros e variáveis locais",
    summary: "Passe dados a um procedimento sem contaminar o resto do programa.",
    explanation: "Os parâmetros comunicam com quem chama o procedimento. LOCaL limita rate ao interior da rotina e evita alterar por acidente uma variável com o mesmo nome.",
    experiment: "Mude a taxa ou chame add_tax uma segunda vez com outro preço.",
    kind: "program",
    code: [
      "100 LET total = 100",
      "110 add_tax 25,total_with_tax",
      '120 PRINT "TOTAL UNCHANGED:" ! total',
      '130 PRINT "WITH TAX:" ! total_with_tax',
      "140 DEFine PROCedure add_tax(price,result)",
      "150   LOCaL rate",
      "160   LET rate = 0.23",
      "170   LET result = price*(1+rate)",
      "180 END DEFine",
    ].join("\n"),
    accent: "red",
    keywords: ["procedure", "parametro", "local", "variavel", "define"],
  }),
  lesson({
    id: "ordenacao-por-insercao",
    chapterNumber: 16,
    chapter: "Ficheiros e ordenação",
    manualReference: "Capítulo 16",
    title: "Ordenar palavras por inserção",
    summary: "Implemente um algoritmo completo usando arrays, ciclos e comparação de strings.",
    explanation: "A ordenação por inserção retira cada item e desloca os maiores até encontrar o lugar certo. A posição zero funciona como sentinela e simplifica o ciclo.",
    experiment: "Troque as palavras em DATA ou acrescente uma oitava palavra, ajustando DIM e os ciclos.",
    kind: "program",
    code: [
      "100 DIM word$(7,8)",
      "110 FOR k = 1 TO 7 : READ word$(k)",
      "120 FOR item = 2 TO 7",
      "130   LET p = item",
      "140   LET hold$ = word$(p)",
      "150   LET word$(0) = hold$",
      "160   REPeat place",
      "170     IF hold$ >= word$(p-1) THEN EXIT place",
      "180     LET word$(p) = word$(p-1)",
      "190     LET p = p-1",
      "200   END REPeat place",
      "210   LET word$(p) = hold$",
      "220 END FOR item",
      "230 FOR k = 1 TO 7 : PRINT ! word$(k) !",
      '240 DATA "EEL","DOG","ANT","GNU","CAT","BUG","FOX"',
    ].join("\n"),
    accent: "yellow",
    keywords: ["ordenar", "sort", "insercao", "array", "repeat", "data", "algoritmo"],
  }),
]);

export function guideLesson(id) {
  return GUIDE_LESSONS.find((candidate) => candidate.id === id) ?? GUIDE_LESSONS[0];
}

export function guideLessonIndex(id) {
  return GUIDE_LESSONS.findIndex((candidate) => candidate.id === guideLesson(id).id);
}

export function adjacentGuideLesson(id, offset) {
  const index = Math.max(0, Math.min(
    GUIDE_LESSONS.length - 1,
    guideLessonIndex(id) + offset,
  ));
  return GUIDE_LESSONS[index];
}

export function guideHash(id) {
  return `#guia/${encodeURIComponent(guideLesson(id).id)}`;
}

export function guideLessonIdFromHash(hash) {
  const match = String(hash ?? "").match(/^#guia\/([^/?#]+)$/u);
  if (!match) return null;
  const id = decodeURIComponent(match[1]);
  return GUIDE_LESSONS.some((candidate) => candidate.id === id) ? id : null;
}

export function matchingGuideLessons(query) {
  const searchable = (value) => String(value ?? "")
    .normalize("NFD")
    .replace(/\p{M}/gu, "")
    .toLocaleLowerCase("pt");
  const needle = searchable(query).trim();
  if (!needle) return GUIDE_LESSONS;
  return GUIDE_LESSONS.filter((candidate) => [
    candidate.title,
    candidate.chapter,
    candidate.summary,
    candidate.explanation,
    candidate.manualReference,
    candidate.note,
    candidate.code,
    ...(candidate.sections ?? []).flatMap((section) => [
      section.title, section.text, ...(section.steps ?? []),
      ...(section.commands ?? []).flatMap((command) => [command.name, command.example, command.description]),
    ]),
    ...candidate.keywords,
  ].some((value) => searchable(value).includes(needle)));
}
