import { MICRODRIVE_FIRST_LESSON, MICRODRIVE_EXTRA_LESSONS } from "./guide-microdrives.js";

function lesson(definition) {
  return Object.freeze({
    ...definition,
    keywords: Object.freeze(definition.keywords),
  });
}

export const GUIDE_LESSONS = Object.freeze([
  lesson({
    id: "primeiro-comando",
    chapterNumber: 1,
    chapter: "The first five minutes",
    manualReference: "Chapter 1",
    title: "Make the QL respond",
    summary: "Send an immediate instruction to SuperBASIC and see the response on screen.",
    explanation: "PRINT displays text or results on screen. Quotation marks indicate that the contents should be treated as text rather than a variable name.",
    experiment: "Change the message in quotation marks and run it again.",
    kind: "command",
    code: 'PRINT "HELLO, SINCLAIR QL"',
    accent: "green",
    keywords: ["print", "text", "command", "console"],
  }),
  lesson({
    id: "primeiro-programa",
    chapterNumber: 2,
    chapter: "First programs",
    manualReference: "Chapter 2",
    title: "Store instructions in a program",
    summary: "Build a small numbered program and leave it ready for RUN.",
    explanation: "Numbered lines are stored in SuperBASIC memory. The QL executes them in order when it receives RUN; NEW clears the previous program.",
    experiment: "Change the value of name$ or add line 140 with another message.",
    kind: "program",
    code: [
      "100 CLS",
      '110 LET name$ = "QL"',
      '120 PRINT "WELCOME TO THE SINCLAIR "; name$',
      '130 PRINT "THIS PROGRAM IS NOW IN MEMORY"',
    ].join("\n"),
    accent: "yellow",
    keywords: ["program", "lines", "run", "let", "variable"],
  }),
  lesson({
    id: "estrela-de-cores",
    chapterNumber: 3,
    chapter: "Drawing on screen",
    manualReference: "Chapter 3",
    title: "A star of coloured lines",
    summary: "Combine colour, random numbers, drawing and repetition in a visual example.",
    explanation: "The QL uses resolution-independent coordinates. FOR repeats the drawing, RND chooses colours and points, and LINE draws each ray of the star.",
    experiment: "Change 24 to 60, or replace PAPER 0 with PAPER 7 to see the contrast.",
    kind: "program",
    code: [
      "100 MODE 8",
      "110 PAPER 0 : CLS",
      "120 FOR ray = 1 TO 24",
      "130   INK RND(1 TO 7)",
      "140   LINE 50,50 TO RND(100),RND(100)",
      "150 END FOR ray",
    ].join("\n"),
    accent: "red",
    keywords: ["graphics", "line", "for", "rnd", "colour"],
  }),
  lesson({
    id: "strings-com-significado",
    chapterNumber: 4,
    chapter: "Text and variables",
    manualReference: "Chapter 4",
    title: "Build and explore text",
    summary: "Join words, count characters and extract letters from a string.",
    explanation: "Variables ending in $ store text. The & operator joins strings, LEN measures them and brackets let you select characters.",
    experiment: "Replace QUANTUM and LEAP with your first name and surname.",
    kind: "program",
    code: [
      "100 CLS",
      '110 LET first$ = "QUANTUM"',
      '120 LET second$ = "LEAP"',
      '130 LET name$ = first$ & " " & second$',
      "140 PRINT name$",
      '150 PRINT "CHARACTERS:" ! LEN(name$)',
      '160 PRINT "INITIALS:" ! first$(1) & second$(1)',
    ].join("\n"),
    accent: "green",
    keywords: ["string", "text", "len", "concatenate", "variable"],
  }),
  lesson(MICRODRIVE_FIRST_LESSON),
  lesson({
    id: "guardar-no-microdrive",
    chapterNumber: 5,
    chapter: "Microdrives, from first steps to copying",
    manualReference: "Chapter 5",
    title: "Save the program on a Microdrive",
    summary: "Save the program currently in memory to mdv1_.",
    explanation: "First follow Start here: a new cartridge and FORMAT. SAVE writes the SuperBASIC program to a file: mdv1_guide means guide in drive 1. Before saving, use LIST to check that there is a program in memory. For a simple trial, type the line 100 PRINT \"HELLO FROM THE MICRODRIVE\" and then run SAVE. Commands without line numbers are immediate instructions; line 100 becomes part of the program.",
    experiment: "After saving, try DIR mdv1_ to check that the file exists.",
    note: "MDV1 must have an inserted, formatted cartridge with writing enabled. If guide already exists, choose SAVE mdv1_guide_v2. SAVE does not export the image to your computer: wait for the motor to stop and use Export .mdv.",
    writesMicrodrive: true,
    kind: "command",
    code: "SAVE mdv1_guide",
    accent: "yellow",
    keywords: ["save", "microdrive", "mdv1", "dir", "load"],
  }),
  lesson({
    id: "formatar-segundo-microdrive",
    chapterNumber: 5,
    chapter: "Microdrives, from first steps to copying",
    manualReference: "Chapter 5 · Microdrives",
    title: "Prepare a cartridge in MDV2",
    summary: "Mount two cartridges and prepare the destination drive for copies.",
    explanation: "Open Software. Select the source cartridge and choose Insert into MDV1. In the manager, select MDV2, choose New cartridge and create a blank cartridge: it is inserted immediately with writing enabled. Run FORMAT to name it work. Inserting keeps the program in memory; Restart and boot from MDV1 restarts the machine and looks for mdv1_boot. Activity in MDV1 does not prevent you from inserting a cartridge into an empty, stopped MDV2.",
    experiment: "When the motor stops, use DIR mdv2_ to see the name and available space.",
    note: "FORMAT erases all contents of MDV2. Use a blank or disposable cartridge. Do not format software cartridges to load them. Wait for the operation to finish; Export .mdv keeps the result on your computer.",
    writesMicrodrive: true,
    microdriveTargets: "mdv2_",
    formatsMicrodrive: true,
    kind: "command",
    code: "FORMAT mdv2_work",
    accent: "red",
    keywords: ["format", "blank", "microdrive", "mdv2", "two drives", "cartridge"],
  }),
  lesson({
    id: "diretorios-dos-dois-microdrives",
    chapterNumber: 5,
    chapter: "Microdrives, from first steps to copying",
    manualReference: "Chapter 5 · Microdrives",
    title: "Check both drives",
    summary: "View files on MDV1 and MDV2 without swapping cartridges.",
    explanation: "The mdv1_ or mdv2_ prefix selects the drive. The underscore is part of the name. DIR shows the cartridge name, space and files. Two cartridges can be mounted at once; QDOS switches between the motors it uses. The red light follows motor selection, including sector searches and the time until it stops, even after text has appeared on screen.",
    experiment: "Try DIR mdv2_ on its own. This emulator has only the QL’s two internal drives: mdv1_ and mdv2_.",
    note: "Requires two formatted, mounted cartridges. A blank cartridge needs FORMAT; an existing software cartridge does not. The library shows which motor is running.",
    kind: "command",
    code: "DIR mdv1_ : DIR mdv2_",
    accent: "green",
    keywords: ["dir", "directory", "list", "microdrive", "mdv1", "mdv2", "light", "motor"],
  }),
  lesson({
    id: "copiar-entre-microdrives",
    chapterNumber: 5,
    chapter: "Microdrives, from first steps to copying",
    manualReference: "Chapter 5 · Microdrives",
    title: "Copy from MDV1 to MDV2",
    summary: "Make a copy of the guide program while keeping the original.",
    explanation: "First use Save the program on a Microdrive to create mdv1_guide. With both cartridges mounted and MDV2 formatted and writable, COPY reads from the source and writes to the destination. COPY preserves the QDOS header, including the type and executable data space. COPY_N is for copies without a header; use COPY between Microdrives.",
    experiment: "Check with DIR mdv2_ and try LOAD mdv2_guide. To copy another file, replace guide in both names.",
    note: "The source can remain Protected. The destination needs free space and must not already contain guide: choose another name or deliberately delete the old copy. Wait for the motors to stop and use Export .mdv for MDV2. COPY copies one file; repeat for every file, including boot and any required data. The base ROM does not provide wildcard copying of an entire cartridge.",
    writesMicrodrive: true,
    microdriveTargets: "mdv2_",
    kind: "command",
    code: "COPY mdv1_guide TO mdv2_guide",
    accent: "yellow",
    keywords: ["copy", "copy_n", "backup", "microdrive", "mdv1", "mdv2", "two drives"],
  }),
  lesson({
    id: "carregar-do-segundo-microdrive",
    chapterNumber: 5,
    chapter: "Microdrives, from first steps to copying",
    manualReference: "Chapter 5 · Microdrives",
    title: "Retrieve the saved program",
    summary: "Load a copy of the guide program from MDV2.",
    explanation: "After the copying example, LOAD reads guide from MDV2 into SuperBASIC memory. Use LIST to examine it and RUN to execute it. LRUN mdv2_guide combines loading and execution. The program must have been saved with SAVE; machine code executables use EXEC or EXEC_W, not LOAD.",
    experiment: "After LOAD, type LIST. To run it directly, try LRUN mdv2_guide.",
    note: "Requires the guide file on MDV2. LOAD replaces the program in memory; first save anything you want to keep. You do not need to remove write protection to read a cartridge.",
    replacesProgram: true,
    kind: "command",
    code: "LOAD mdv2_guide",
    accent: "yellow",
    keywords: ["load", "lrun", "run", "list", "microdrive", "mdv2", "executable"],
  }),
  lesson({
    id: "arrancar-software-microdrive",
    chapterNumber: 5,
    chapter: "Microdrives, from first steps to copying",
    manualReference: "Chapter 5 · Microdrives",
    title: "Boot software and recognise errors",
    summary: "Use the cartridge’s BOOT and distinguish BASIC programs from executables.",
    explanation: "DIR mdv1_ lets you check whether boot exists. LRUN mdv1_boot loads and runs that BASIC program. Alternatively, Restart and boot from MDV1 in the manager uses the cartridge already inserted, restarts the QL and sends F1. For a QDOS executable use, for example, EXEC_W mdv1_program. Some programs expect data on MDV2: also insert the second cartridge before booting.",
    experiment: "If you want to examine BOOT before running it, use LOAD mdv1_boot and LIST to find out which names and drives it uses.",
    note: "Not found: check the drive and name with DIR. Bad medium: check that the image is valid; do not use FORMAT to repair software you want to keep. Bad parameter when using EXEC: the file may lack an executable header. Not implemented or Out of memory may indicate extensions or extra RAM required by the program. The emulator has 128 KiB; ZIP/QLPAK conversion does not add Toolkit II or change disc references inside every program.",
    replacesProgram: true,
    kind: "command",
    code: "LRUN mdv1_boot",
    accent: "green",
    keywords: ["boot", "exec", "exec_w", "lrun", "error", "load", "microdrive", "bad medium", "not found"],
  }),
  lesson({
    id: "copiar-de-volta-microdrive",
    chapterNumber: 5,
    chapter: "Microdrives, from first steps to copying",
    manualReference: "Chapter 5 · Microdrives",
    title: "Copy back with another name",
    summary: "Read from MDV2 and create guide_copy on MDV1.",
    explanation: "The source and destination can swap roles. The name after TO can be different: guide_copy avoids replacing the original guide file. The command does not change the BASIC program in memory.",
    experiment: "Check with DIR mdv1_. You can also copy within one drive using COPY mdv2_guide TO mdv2_guide_copy, if there is space.",
    note: "Requires the guide copy on MDV2 and a writable MDV1 with free space and no previous guide_copy file. When finished, save the MDV1 image to keep this new copy.",
    writesMicrodrive: true,
    microdriveTargets: "mdv1_",
    kind: "command",
    code: "COPY mdv2_guide TO mdv1_guide_copy",
    accent: "green",
    keywords: ["copy", "backup", "rename", "microdrive", "mdv1", "mdv2"],
  }),
  lesson({
    id: "apagar-copia-microdrive",
    chapterNumber: 5,
    chapter: "Microdrives, from first steps to copying",
    manualReference: "Chapter 5 · Microdrives",
    title: "Delete only the trial copy",
    summary: "Free the space used by guide_copy on MDV1.",
    explanation: "DELETE removes the specified file, keeping the others. Use DIR mdv1_ first to check the name. To repeat a copy with the same destination, you can delete that destination first, if you are sure you no longer need it.",
    experiment: "After DELETE, check with DIR mdv1_ that guide is still present.",
    note: "This example deletes mdv1_guide_copy, created in the previous lesson. Requires a writable MDV1. QDOS has no undo; keep an exported image if you want to be able to recover the previous contents.",
    writesMicrodrive: true,
    microdriveTargets: "mdv1_",
    kind: "command",
    code: "DELETE mdv1_guide_copy",
    accent: "red",
    keywords: ["delete", "space", "microdrive", "mdv1", "backup"],
  }),
  ...MICRODRIVE_EXTRA_LESSONS.map(lesson),
  lesson({
    id: "arrays-e-ciclos-for",
    chapterNumber: 6,
    chapter: "Lists and repetition",
    manualReference: "Chapter 6",
    title: "Six throws in an array",
    summary: "Store a sequence of numbers and work through it with FOR.",
    explanation: "DIM reserves an indexed collection. The first loop fills the array and the second retrieves each position, showing how data and repetition work together.",
    experiment: "Increase the array to 12 positions and simulate two dice with RND(1 TO 6)+RND(1 TO 6).",
    kind: "program",
    code: [
      "100 DIM score(6)",
      "110 FOR k = 1 TO 6 : LET score(k) = RND(1 TO 6)",
      '120 PRINT "SIX THROWS:"',
      "130 FOR k = 1 TO 6 : PRINT ! score(k) !",
    ].join("\n"),
    accent: "red",
    keywords: ["array", "dim", "for", "rnd", "list", "loop"],
  }),
  lesson({
    id: "primeira-procedure",
    chapterNumber: 7,
    chapter: "Procedures",
    manualReference: "Chapter 7",
    title: "Give a task a name",
    summary: "Define a reusable procedure that draws a square.",
    explanation: "DEFine PROCedure creates a new SuperBASIC instruction. Parameters let the same procedure work with different sizes and positions.",
    experiment: "Add square 20,60,20 before the definition to draw another square.",
    kind: "program",
    code: [
      "100 PAPER 0 : CLS",
      "110 INK 4",
      "120 square 30,35,35",
      "130 DEFine PROCedure square(side,x,y)",
      "140   LINE x,y TO x+side,y TO x+side,y+side TO x,y+side TO x,y",
      "150 END DEFine",
    ].join("\n"),
    accent: "green",
    keywords: ["procedure", "define", "parameters", "line", "subroutine"],
  }),
  lesson({
    id: "superbasic-estruturado",
    chapterNumber: 8,
    chapter: "Structured programs",
    manualReference: "Chapter 8",
    title: "Make decisions without jumps",
    summary: "Use a complete IF block inside a readable loop.",
    explanation: "The structured IF…ELSE…END IF form keeps the program’s paths visible. MOD lets you distinguish even numbers from odd ones.",
    experiment: "Change the FOR limit or test divisibility by 3.",
    kind: "program",
    code: [
      "100 FOR value = 1 TO 12",
      "110   IF value MOD 2 = 0 THEN",
      '120     PRINT value ! "EVEN"',
      "130   ELSE",
      '140     PRINT value ! "ODD"',
      "150   END IF",
      "160 END FOR value",
    ].join("\n"),
    accent: "yellow",
    keywords: ["if", "else", "end if", "mod", "structure", "decision"],
  }),
  lesson({
    id: "tipos-e-aritmetica",
    chapterNumber: 9,
    chapter: "Numbers and types",
    manualReference: "Chapter 9",
    title: "Divide, round and measure",
    summary: "Compare real division, integer division, remainders and square roots.",
    explanation: "DIV returns the integer quotient and MOD the remainder. SQRT calculates the square root; INT helps with rounding. The % suffix identifies an integer variable.",
    experiment: "Try other values of total and groups% and predict each result.",
    kind: "program",
    code: [
      "100 LET total = 17",
      "110 LET groups% = 5",
      '120 PRINT "DIVISION:" ! total/groups%',
      '130 PRINT "INTEGER DIVISION:" ! total DIV groups%',
      '140 PRINT "REMAINDER:" ! total MOD groups%',
      '150 PRINT "SQUARE ROOT:" ! SQRT(total)',
      '160 PRINT "ROUNDED:" ! INT(SQRT(total)+0.5)',
    ].join("\n"),
    accent: "red",
    keywords: ["number", "integer", "div", "mod", "sqrt", "int", "arithmetic"],
  }),
  lesson({
    id: "logica-booleana",
    chapterNumber: 10,
    chapter: "Logic",
    manualReference: "Chapter 10",
    title: "A truth table",
    summary: "See AND, OR and XOR for every combination of zero and one.",
    explanation: "Logical operators combine conditions. This small table shows when each operator produces false (0) or true (1).",
    experiment: "Add a column with NOT a and observe the values produced.",
    kind: "program",
    code: [
      '100 PRINT "A B  AND OR XOR"',
      "110 FOR a = 0 TO 1",
      "120   FOR b = 0 TO 1",
      "130     PRINT a ! b ! (a AND b) ! (a OR b) ! (a XOR b)",
      "140   END FOR b",
      "150 END FOR a",
    ].join("\n"),
    accent: "green",
    keywords: ["logic", "and", "or", "xor", "not", "boolean"],
  }),
  lesson({
    id: "fatiar-e-procurar-strings",
    chapterNumber: 11,
    chapter: "String operations",
    manualReference: "Chapter 11",
    title: "Find and replace words",
    summary: "Select ranges of characters and find text with INSTR.",
    explanation: "A slice such as text$(10 TO 16) reads or replaces part of a string. INSTR returns the position at which an expression appears.",
    experiment: "Search for LEAP and replace another slice with a word of the same length.",
    kind: "program",
    code: [
      '100 LET text$ = "SINCLAIR QUANTUM LEAP"',
      "110 PRINT text$(1 TO 8)",
      "120 PRINT text$(10 TO 16)",
      '130 LET pos = "QUANTUM" INSTR text$',
      '140 PRINT "FOUND AT:" ! pos',
      '150 LET text$(10 TO 16) = "DIGITAL"',
      "160 PRINT text$",
    ].join("\n"),
    accent: "yellow",
    keywords: ["string", "instr", "slice", "replace", "search"],
  }),
  lesson({
    id: "circulos-e-cor",
    chapterNumber: 12,
    chapter: "Graphics and windows",
    manualReference: "Chapter 12",
    title: "Concentric circles",
    summary: "Explore the QL palette with circles of increasing radius.",
    explanation: "CIRCLE takes the centre and radius in graphics coordinates. INK chooses the colour used for each new circle.",
    experiment: "Change the centre or use closer radius values to create a target.",
    kind: "program",
    code: [
      "100 MODE 8",
      "110 PAPER 0 : CLS",
      "120 FOR colour = 1 TO 7",
      "130   INK colour",
      "140   CIRCLE 50,50,5+colour*5",
      "150 END FOR colour",
    ].join("\n"),
    accent: "red",
    keywords: ["circle", "ink", "paper", "graphics", "colour"],
  }),
  lesson({
    id: "janela-independente",
    chapterNumber: 12,
    chapter: "Graphics and windows",
    manualReference: "Chapter 12",
    title: "Open a separate window",
    summary: "Create a screen channel, colour it and close it without affecting the main console.",
    explanation: "Channels marked with # let you direct each command to a device or window. OPEN creates window #4; commands with #4 act only on that window.",
    experiment: "Change the scr_ dimensions or the PAPER and INK colours.",
    kind: "program",
    code: [
      "100 OPEN #4,scr_220x100a20x20",
      "110 PAPER #4,1 : INK #4,7 : CLS #4",
      "120 BORDER #4,4,2",
      '130 PRINT #4,"A WINDOW OF ITS OWN"',
      "140 PAUSE 100",
      "150 CLOSE #4",
    ].join("\n"),
    accent: "green",
    keywords: ["window", "channel", "open", "screen", "scr"],
  }),
  lesson({
    id: "ficheiro-sequencial",
    chapterNumber: 12,
    chapter: "Channels and files",
    manualReference: "Chapter 12",
    title: "Write and read a file",
    summary: "Save ten results in a sequential file and read them back.",
    explanation: "OPEN_NEW creates the file, PRINT # writes to its channel and OPEN_IN opens it again for reading. Always use CLOSE to release the channel at the end.",
    experiment: "Save cubes instead of squares or increase the number of values.",
    note: "Requires a formatted cartridge in mdv1_ with writing enabled. OPEN_NEW gives an error if guide_data already exists: use another name or deliberately delete the previous file with DELETE mdv1_guide_data.",
    writesMicrodrive: true,
    kind: "program",
    code: [
      "100 OPEN_NEW #6,mdv1_guide_data",
      "110 FOR n = 1 TO 10",
      "120   PRINT #6,n*n",
      "130 END FOR n",
      "140 CLOSE #6",
      "150 OPEN_IN #6,mdv1_guide_data",
      "160 FOR n = 1 TO 10",
      "170   INPUT #6,value",
      "180   PRINT ! value !",
      "190 END FOR n",
      "200 CLOSE #6",
    ].join("\n"),
    accent: "green",
    keywords: ["file", "open_new", "open_in", "input", "microdrive", "mdv1"],
  }),
  lesson({
    id: "dois-canais-dois-microdrives",
    chapterNumber: 12,
    chapter: "Channels and files",
    manualReference: "Chapter 12 · Microdrives",
    title: "Read from one drive and write to the other",
    summary: "Open two channels at once and transfer values to the end of the file, using EOF.",
    explanation: "First run Write and read a file to create mdv1_guide_data. #6 reads from MDV1 and #7 writes to MDV2. Both channels stay open; QDOS manages the buffers and switches motors. EOF is tested before each INPUT to avoid reading past the end even if the number of values changes. PRINT writes the value and CLOSE closes the channels. For an exact copy of any file, use COPY.",
    experiment: "Change PRINT #7,value to PRINT #7,value*2, choose a new destination name and run it again to transform the values while copying.",
    note: "Requires guide_data with numeric values, one per line, on MDV1, and a formatted, writable MDV2 with no existing guide_copy. The previous example creates ten values, but this loop accepts a different quantity. When finished, wait for the motors to stop and save MDV2. If you interrupt the program, close the open channels with CLOSE #6 and CLOSE #7 before swapping cartridges.",
    writesMicrodrive: true,
    microdriveTargets: "mdv2_",
    kind: "program",
    code: [
      "100 OPEN_IN #6,mdv1_guide_data",
      "110 OPEN_NEW #7,mdv2_guide_copy",
      "120 REPeat copying",
      "125   IF EOF(#6) THEN EXIT copying",
      "130   INPUT #6,value",
      "140   PRINT #7,value",
      "150 END REPeat copying",
      "160 CLOSE #7",
      "170 CLOSE #6",
      '180 PRINT "COPY COMPLETE"',
    ].join("\n"),
    accent: "yellow",
    keywords: ["channel", "open_in", "open_new", "close", "eof", "copy", "microdrive", "mdv1", "mdv2", "simultaneous"],
  }),
  lesson({
    id: "array-bidimensional",
    chapterNumber: 13,
    chapter: "Multidimensional arrays",
    manualReference: "Chapter 13",
    title: "A multiplication table",
    summary: "Organise values in rows and columns with a two-dimensional array.",
    explanation: "DIM table(3,3) creates a grid. Two indices identify each cell and two loops work through its rows and columns.",
    experiment: "Turn the 3×3 table into a 6×6 table.",
    kind: "program",
    code: [
      "100 DIM table(3,3)",
      "110 FOR row = 1 TO 3",
      "120   FOR col = 1 TO 3",
      "130     LET table(row,col) = row*col",
      "140     PRINT ! table(row,col) !",
      "150   END FOR col",
      "160   PRINT",
      "170 END FOR row",
    ].join("\n"),
    accent: "yellow",
    keywords: ["array", "dim", "matrix", "table", "line", "column"],
  }),
  lesson({
    id: "estruturas-aninhadas",
    chapterNumber: 14,
    chapter: "Nested structures",
    manualReference: "Chapter 14",
    title: "A grid of coloured points",
    summary: "Combine two loops to work through coordinates in two dimensions.",
    explanation: "The outer loop selects each row and the inner loop works through the columns. Nesting structures lets you express complex patterns without repeating code.",
    experiment: "Reduce STEP to 5 or replace POINT with CIRCLE x,y,2.",
    kind: "program",
    code: [
      "100 PAPER 0 : CLS",
      "110 FOR y = 20 TO 80 STEP 10",
      "120   FOR x = 20 TO 80 STEP 10",
      "130     INK RND(1 TO 7)",
      "140     POINT x,y",
      "150   END FOR x",
      "160 END FOR y",
    ].join("\n"),
    accent: "red",
    keywords: ["nested", "for", "point", "grid", "step"],
  }),
  lesson({
    id: "selecao-multipla",
    chapterNumber: 14,
    chapter: "Nested structures",
    manualReference: "Chapter 14",
    title: "Choose between several paths",
    summary: "Use SELect ON to handle alternatives clearly.",
    explanation: "SELect ON brings several related choices together in a single block. Each ON clause handles a possible value without a long chain of IF statements.",
    experiment: "Add more directions and increase the RND range.",
    kind: "program",
    code: [
      "100 LET choice = RND(1 TO 4)",
      "110 SELect ON choice",
      "120   ON choice = 1",
      '130     PRINT "NORTH"',
      "140   ON choice = 2",
      '150     PRINT "EAST"',
      "160   ON choice = 3",
      '170     PRINT "SOUTH"',
      "180   ON choice = 4",
      '190     PRINT "WEST"',
      "200 END SELect",
    ].join("\n"),
    accent: "green",
    keywords: ["select", "on", "choice", "alternative", "condition"],
  }),
  lesson({
    id: "funcao-com-resultado",
    chapterNumber: 15,
    chapter: "Procedures and functions",
    manualReference: "Chapter 15",
    title: "Create a function",
    summary: "Define a cube function that calculates and returns a value.",
    explanation: "A FuNction can be used within an expression. RETurn passes the result back to the point where the function was called.",
    experiment: "Create a square function or change the loop range.",
    kind: "program",
    code: [
      "100 FOR n = 1 TO 8",
      "110   PRINT n ! cube(n)",
      "120 END FOR n",
      "130 DEFine FuNction cube(value)",
      "140   RETurn value*value*value",
      "150 END DEFine",
    ].join("\n"),
    accent: "yellow",
    keywords: ["function", "define", "return", "result"],
  }),
  lesson({
    id: "parametros-e-variaveis-locais",
    chapterNumber: 15,
    chapter: "Procedures and functions",
    manualReference: "Chapter 15",
    title: "Parameters and local variables",
    summary: "Pass data to a procedure without affecting the rest of the program.",
    explanation: "Parameters communicate with the code calling the procedure. LOCaL restricts rate to the routine and prevents accidentally changing a variable with the same name.",
    experiment: "Change the rate or call add_tax a second time with another price.",
    kind: "program",
    code: [
      "100 LET total = 100",
      "110 add_tax 25,total_with_tax",
      '120 PRINT "TOTAL UNCHANGED:" ! total',
      '130 PRINT "WITH TAX:" ! total_with_tax',
      "140 DEFine PROCedure add_tax(price,result)",
      "150   LOCaL rate",
      "160   LET rate = 0.23",
      "170   LET result = price*(1+rate)",
      "180 END DEFine",
    ].join("\n"),
    accent: "red",
    keywords: ["procedure", "parameter", "local", "variable", "define"],
  }),
  lesson({
    id: "ordenacao-por-insercao",
    chapterNumber: 16,
    chapter: "Files and sorting",
    manualReference: "Chapter 16",
    title: "Sort words by insertion",
    summary: "Implement a complete algorithm using arrays, loops and string comparisons.",
    explanation: "Insertion sort takes each item and shifts larger items until it finds the right place. Position zero acts as a sentinel and simplifies the loop.",
    experiment: "Change the words in DATA or add an eighth word, adjusting DIM and the loops.",
    kind: "program",
    code: [
      "100 DIM word$(7,8)",
      "110 FOR k = 1 TO 7 : READ word$(k)",
      "120 FOR item = 2 TO 7",
      "130   LET p = item",
      "140   LET hold$ = word$(p)",
      "150   LET word$(0) = hold$",
      "160   REPeat place",
      "170     IF hold$ >= word$(p-1) THEN EXIT place",
      "180     LET word$(p) = word$(p-1)",
      "190     LET p = p-1",
      "200   END REPeat place",
      "210   LET word$(p) = hold$",
      "220 END FOR item",
      "230 FOR k = 1 TO 7 : PRINT ! word$(k) !",
      '240 DATA "EEL","DOG","ANT","GNU","CAT","BUG","FOX"',
    ].join("\n"),
    accent: "yellow",
    keywords: ["sort", "insertion", "array", "repeat", "data", "algorithm"],
  }),
]);

export function guideLesson(id) {
  return GUIDE_LESSONS.find((candidate) => candidate.id === id) ?? GUIDE_LESSONS[0];
}

export function guideLessonIndex(id) {
  return GUIDE_LESSONS.findIndex((candidate) => candidate.id === guideLesson(id).id);
}

export function adjacentGuideLesson(id, offset) {
  const index = Math.max(0, Math.min(
    GUIDE_LESSONS.length - 1,
    guideLessonIndex(id) + offset,
  ));
  return GUIDE_LESSONS[index];
}

export function guideHash(id) {
  return `#guia/${encodeURIComponent(guideLesson(id).id)}`;
}

export function guideLessonIdFromHash(hash) {
  const match = String(hash ?? "").match(/^#guia\/([^/?#]+)$/u);
  if (!match) return null;
  const id = decodeURIComponent(match[1]);
  return GUIDE_LESSONS.some((candidate) => candidate.id === id) ? id : null;
}

export function matchingGuideLessons(query) {
  const searchable = (value) => String(value ?? "")
    .normalize("NFD")
    .replace(/\p{M}/gu, "")
    .toLocaleLowerCase("en-GB");
  const needle = searchable(query).trim();
  if (!needle) return GUIDE_LESSONS;
  return GUIDE_LESSONS.filter((candidate) => [
    candidate.title,
    candidate.chapter,
    candidate.summary,
    candidate.explanation,
    candidate.manualReference,
    candidate.note,
    candidate.code,
    ...(candidate.sections ?? []).flatMap((section) => [
      section.title, section.text, ...(section.steps ?? []),
      ...(section.commands ?? []).flatMap((command) => [command.name, command.example, command.description]),
    ]),
    ...candidate.keywords,
  ].some((value) => searchable(value).includes(needle)));
}
